---
abstract: 'Fuse binding for MogileFS'
author:
  - 'Daniel Frett <daniel.frett@gmail.com>'
build_requires:
  Test::More: 0
configure_requires:
  Module::Build: 0.36
dynamic_config: 1
generated_by: 'Module::Build version 0.4, CPAN::Meta::Converter version 2.120630'
license: bsd
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: MogileFS-Client-Fuse
provides:
  MogileFS::Client::Fuse:
    file: lib/MogileFS/Client/Fuse.pm
    version: 0.03
  MogileFS::Client::Fuse::BufferedFile:
    file: lib/MogileFS/Client/Fuse/BufferedFile.pm
    version: 0.03
  MogileFS::Client::Fuse::Constants:
    file: lib/MogileFS/Client/Fuse/Constants.pm
    version: 0
  MogileFS::Client::Fuse::File:
    file: lib/MogileFS/Client/Fuse/File.pm
    version: 0.03
  MogileFS::Client::Fuse::FilePaths:
    file: lib/MogileFS/Client/Fuse/FilePaths.pm
    version: 0.03
requires:
  Fuse: 0.11
  MogileFS::Client::FilePaths: 0
  Params::Validate: 0
  Scalar::Util: 0
resources:
  license: http://www.opensource.org/licenses/BSD-3-Clause
  repository: https://github.com/frett/MogileFS-Fuse
version: 0.03
