---
abstract: 'Fuse binding for MogileFS'
author: []
configure_requires:
  Module::Build: 0.36
generated_by: 'Module::Build version 0.3624'
license: mit
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: MogileFS-Fuse
provides:
  MogileFS::Fuse:
    file: lib/MogileFS/Fuse.pm
    version: v0.0.1
  MogileFS::Fuse::BufferedFile:
    file: lib/MogileFS/Fuse/BufferedFile.pm
    version: v0.0.1
  MogileFS::Fuse::Constants:
    file: lib/MogileFS/Fuse/Constants.pm
  MogileFS::Fuse::File:
    file: lib/MogileFS/Fuse/File.pm
    version: v0.0.1
  MogileFS::Fuse::FilePaths:
    file: lib/MogileFS/Fuse/FilePaths.pm
    version: v0.0.1
requires:
  Fuse: 0.11
  MogileFS::Client::FilePaths: 0
  Params::Validate: 0
  Scalar::Util: 0
resources:
  license: http://www.opensource.org/licenses/mit-license.php
version: v0.0.1
